[package]
name = "dioxus-radio"
version = "0.1.0"
edition = "2021"
readme = "./README.md"
homepage = "https://github.com/dioxus-community/dioxus-radio"
repository = "https://github.com/dioxus-community/dioxus-radio"
keywords = ["dioxus"]
categories = ["gui"]
license = "./LICENSE.md"

[dependencies]
dioxus = { version = "0.4", default-features = false, features = ["macro", "hooks"] }

[dev-dependencies]
dioxus-desktop = "0.4.3"
dioxus = { version = "0.4", default-features = true }